[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/cardapio/massas"
  to = "/cardapio/pizzas"
  status = 301

[[redirects]]
  from = "/cardapio/molhos"
  to = "/cardapio/pizzas"
  status = 301

[[redirects]]
  from = "/cardapio/recheios"
  to = "/cardapio/pizzas"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
